# Generated by Django 5.0.7 on 2024-08-28 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.mapobject')),
            ],
        ),
        migrations.CreateModel(
            name='BusStopOrderA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='BusStopOrderB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('center_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.mapobject')),
            ],
        ),
        migrations.AddField(
            model_name='busstop',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='route.city'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path_a', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_a', to='map.mapobject')),
                ('path_a_stops', models.ManyToManyField(blank=True, related_name='path_a_stops', through='route.BusStopOrderA', to='route.busstop')),
                ('path_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_b', to='map.mapobject')),
                ('path_b_stops', models.ManyToManyField(blank=True, related_name='path_b_stops', through='route.BusStopOrderB', to='route.busstop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='busstoporderb',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AddField(
            model_name='busstopordera',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
    ]
