# Generated by Django 5.0.4 on 2024-05-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('route', '0002_alter_route_path_a_alter_route_path_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.mapobject'),
        ),
        migrations.AlterField(
            model_name='route',
            name='path_a',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_a', to='map.mapobject'),
        ),
        migrations.AlterField(
            model_name='route',
            name='path_b',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_b', to='map.mapobject'),
        ),
    ]
