# Generated by Django 5.0.7 on 2024-09-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_routetype_route_route_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstopordera',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='busstoporderb',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='busstopordera',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstoporderb',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
