# Generated by Django 5.0.4 on 2024-05-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_remove_route_assigned_stops_route_path_a_stops_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name']},
        ),
    ]
