# Generated by Django 5.0.4 on 2024-05-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('route', '0005_alter_busstop_options_alter_route_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.mapobject'),
        ),
    ]
