# Generated by Django 5.0.4 on 2024-06-02 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_objectpoint_map_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlinestring',
            name='map_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line', to='map.mapobject'),
        ),
    ]
