# Generated by Django 5.0.4 on 2024-07-18 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.IntegerField()),
                ('course', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.mapobject')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='route.route')),
                ('transport_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transporttype')),
            ],
        ),
    ]
