# Generated by Django 5.0.7 on 2024-09-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['imei']},
        ),
        migrations.AlterModelOptions(
            name='transporttype',
            options={'ordering': ['name']},
        ),
    ]
